[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[tools]
pre-commit = "4.2.0"
uv = "0.7.2"

[tasks.lint]
run = "uv run ruff check"

[tasks.check-format]
run = "uv run ruff check"

[tasks.format]
run = "uv run ruff format"

[tasks.build]
run = "uv build"

[hooks]
# Install pre-commit hooks if not in CI environment
postinstall = '[ -z "$CI" ] && pre-commit install --install-hooks || true'
