[settings]
python.uv_venv_auto = true

[tools]
pre-commit = "4.2.0"
uv = "0.7.2"

[tasks.lint]
run = "uv run ruff check"

[tasks.format]
run = "uv run ruff format"

[hooks]
postinstall = "pre-commit install --install-hooks"
